language: go

go:
  - '1.11'
  - '1.12'
  - master

git:
  depth: 1

notifications:
  email: false

matrix:
  allow_failures:
    - go: master
install: go get

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $HOME/bin v1.16.0

script:
  - go build -v
  - go test -v -coverprofile=coverage.txt -covermode=atomic ./...
  - golangci-lint run

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

env:
  CODECOV_TOKEN:
    secure: dl2AAtAb5D1/+YyvUNrJ/25dRPSQIr44JGGsx4GK4EMVt9oi7LYRMI05+F04QAy76O3FexNywkCUi9M152BnqDx0mTg0UVAsGGNODdxjkaKNT7svD4T5sJnnjBWb/KMpXpxNDkrGPt56aCBTo3sTMfP0crDvIIx5mwLKAYeTDWV9dGxt20sY98VidDsB1esyA7/vd381rt7cfN5i2Y3D8wglMq2ZTbVcoHviIiEAKdfSldS8g1Tmk18oYfZah9/uZM0en4070ObO5Ui6l4qydygh0gSkmTK3vdqTqZEi2l5Nt/jiTGPqV7mcO7J6SNDzKTHdKZhtdqwsNDVe2dyKgNfG5L1qRApphRuapgofYA8k8i9nbaQJHdP9+Q1DExdwE0wWjEcFIUXg8uMdGqNnBt+h+TZf95i8MFrHZhBLE1GYWx/i8hSpq7Spx5TSztJmhFCSsuqJZryb30vkDDEQGd/pSXMXKtKVcgJHcaT7KYbjFtVe3VNxh9GDZdGQ7doZKxvY+tht1daJzjbhVlzAC9cCevIMyEjPVXdJD0kN/nSlPQJ/3ZhGmNUjkmunfyHwwUHT51YrF50K+jatkHNmS0BG3LCDo7qhHPQxyCg2ckZWUx70ItqguJa6Jg9//SQ5GGN5C2UoQDXPVYOaBJSs8ZOkNsg9HXC5G1CXK9taV2Q=
