language: go

go:
  - '1.13'
  - master

git:
  depth: 1

notifications:
  email: false

matrix:
  allow_failures:
    - go: master

install: go get ./...

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $HOME/bin v1.21.0
  - go get -u golang.org/x/lint/golint

script:
  - go test -v -coverprofile=coverage.txt -covermode=atomic ./...
  - $HOME/bin/golangci-lint run
  - golint -set_exit_status $(go list ./...)

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - GO111MODULE=on
